trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: stage1
  jobs: 
  - job: job1
    steps:
    - script: echo Hello, world!
    - script: |
        echo building yml script,
        echo See https://aka.ms/yaml



